name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install coverage

      - name: Run pytest with coverage
        run: |
          coverage run -m pytest

      - name: Generate coverage report
        run: |
          coverage xml -i
          coverage html -i

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
